### ISSUE TITLE
database, authorization, etc

### ISSUE THREAD

**Issue by sainthasras** [deriegle/dart-express#5]
Hello, I am new to the world of Dart server-side programming. I will like to ask if you have authorization and database support for dart-express.

**Comment by deriegle** [comment]
Currently, I do not but you can integrate with any other database or authorization libraries on pub.dev like [this one](https://pub.dev/packages/database)

I am working on creating a small database library that will work really well with this soon. Sorry it is not available now.

**Comment by sainthasras** [comment]
Right. Thanks for the response.
